### ISSUE TITLE
Broken links in name-and-organize-schema-files.md

### ISSUE THREAD

**Issue by Hwesta** [bytebase/bytebase.com#243]
In `content/docs/vcs-integration/name-and-organize-schema-files.md`, there are links to example directory structures hosted at https://gitlab.bytebase.com but that URL doesn't exist. 

Also, the links to the example issues at https://demo.bytebase.com/ don't load fully for me. It hangs with a loading wheel.

**Comment by tianzhou** [comment]
Thanks for reporting. The doc and demo should have been fixed.
