### ISSUE TITLE
TOC extends to the botton way too far

### ISSUE THREAD

**Issue by 3DRX** [bytebase/bytebase.com#283]
Browser: brave v1.61.120(chromium based)
Expected Behavior: The height of TABLE OF CONTENTS should be less than view height, and scroll when content length is larger.
Instead: The TOC doesn't scroll and extends all the way down to the bottom of the page.

![image](https://github.com/bytebase/bytebase.com/assets/67278980/c76585da-06b1-449a-b07f-b1fc3c94c6eb)

**Comment by boojack** [comment]
Thanks for your report, it'll be fixed with https://github.com/bytebase/bytebase.com/pull/286
